name: MLAKSDeployment
dependencies:
  - python=3.5
  - pip:
    - ipykernel==4.8.2
    - pandas==0.23.3
    - matplotlib==2.2.2
    - aiohttp==3.3.2
    - toolz==0.9.0
    - tqdm==4.23.4
    - tornado==4.5.3
    - azure-cli==2.0.41
    - scikit-learn==0.19.1
    - lightgbm==2.1.2
